trigger:
- main

pool:
  name: Default

steps:
- script: |
    git clone https://github.com/Coralinesp/TeamTasks
    cd repo
    git remote add azure https://dev.azure.com/ORG/PROYECT/_git/REPO
    git push azure main
  displayName: 'Sync repos'
