trigger:
- main

pool:
  name: Default

steps:
- script: |
    git clone https://github.com/Coralinesp/TeamTasks
    cd TeamTasks
    git remote add azure https://$(AZURE_PAT)@dev.azure.com/LoPasaHambre/LosPasaHambre/_git/LosPasaHambre
    git push azure main
  displayName: 'Sync repos'
